=== OleksandrBohatyrov/xmlReis/xmlReis.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Reisid">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" name="Firma">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Firma">
								<xs:complexType>
									<xs:attribute name="Name" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element maxOccurs="unbounded" name="Transport">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Transport">
											<xs:complexType>
												<xs:attribute name="Type" type="xs:string" use="required" />
											</xs:complexType>
										</xs:element>
										<xs:element name="Reis">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Lennujaam">
														<xs:complexType>
															<xs:attribute name="Name" type="xs:string" use="required" />
														</xs:complexType>
													</xs:element>
													<xs:element name="Kuupaev" type="xs:date" />
													<xs:element name="Hind" type="xs:unsignedShort" />
													<xs:element name="Firma" type="xs:string" />
													<xs:element name="Algus_Koht" type="xs:string" />
													<xs:element name="LÃµpp_Koht" type="xs:string" />
													<xs:element name="FirmaRating" type="xs:unsignedByte" />
													<xs:element name="Ekskursioonid" type="xs:unsignedShort" />
													<xs:element name="Majutus" type="xs:unsignedShort" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== OleksandrBohatyrov/xmlReis/xmlReis.xml
<Reisid xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"

       xsi:noNamespaceSchemaLocation="xmlReis.xsd">
	<Firma>
		<Firma Name="Avamba" />
		<Transport>
			<Transport Type="United" />
			<Reis>
				<Lennujaam Name="Oki Airport" />
				<Kuupaev>2024-01-01</Kuupaev>
				<Hind>747</Hind>
				<Firma>Avamba</Firma>
				<Algus_Koht>Makilala</Algus_Koht>
				<Lõpp_Koht>Shisandaogou</Lõpp_Koht>
				<FirmaRating>5</FirmaRating>
				<Ekskursioonid>380</Ekskursioonid>
				<Majutus>1236</Majutus>
			</Reis>
		</Transport>
	</Firma>
	<Firma>
		<Firma Name="Avamm" />
		<Transport>
			<Transport Type="United" />
			<Reis>
				<Lennujaam Name="Laredo International Airport" />
				<Kuupaev>2024-03-22</Kuupaev>
				<Hind>797</Hind>
				<Firma>Avamm</Firma>
				<Algus_Koht>Bukonyo</Algus_Koht>
				<Lõpp_Koht>Dordrecht</Lõpp_Koht>
				<FirmaRating>4</FirmaRating>
				<Ekskursioonid>170</Ekskursioonid>
				<Majutus>2850</Majutus>
			</Reis>
		</Transport>
	</Firma>
	<Firma>
		<Firma Name="Babbleopia" />
		<Transport>
			<Transport Type="United" />
			<Reis>
				<Lennujaam Name="Kugluktuk Airport" />
				<Kuupaev>2024-02-08</Kuupaev>
				<Hind>1880</Hind>
				<Firma>Babbleopia</Firma>
				<Algus_Koht>Koltushi</Algus_Koht>
				<Lõpp_Koht>Corredoura</Lõpp_Koht>
				<FirmaRating>1</FirmaRating>
				<Ekskursioonid>891</Ekskursioonid>
				<Majutus>2339</Majutus>
			</Reis>
		</Transport>
	</Firma>
	<Firma>
		<Firma Name="Babbleset" />
		<Transport>
			<Transport Type="Alaska" />
			<Reis>
				<Lennujaam Name="Jataí Airport" />
				<Kuupaev>2023-10-20</Kuupaev>
				<Hind>955</Hind>
				<Firma>Babbleset</Firma>
				<Algus_Koht>Concepción</Algus_Koht>
				<Lõpp_Koht>Novo Selo</Lõpp_Koht>
				<FirmaRating>4</FirmaRating>
				<Ekskursioonid>721</Ekskursioonid>
				<Majutus>2415</Majutus>
			</Reis>
		</Transport>
	</Firma>
	<Firma>
		<Firma Name="Blogspan" />
		<Transport>
			<Transport Type="American" />
			<Reis>
				<Lennujaam Name="Ayapel Airport" />
				<Kuupaev>2024-08-30</Kuupaev>
				<Hind>1308</Hind>
				<Firma>Blogspan</Firma>
				<Algus_Koht>Cañas</Algus_Koht>
				<Lõpp_Koht>Cravo Norte</Lõpp_Koht>
				<FirmaRating>1</FirmaRating>
				<Ekskursioonid>779</Ekskursioonid>
				<Majutus>1092</Majutus>
			</Reis>
		</Transport>
	</Firma>
	<Firma>
		<Firma Name="Brainsphere" />
		<Transport>
			<Transport Type="Alaska" />
			<Reis>
				<Lennujaam Name="Incirlik Air Base" />
				<Kuupaev>2023-12-20</Kuupaev>
				<Hind>295</Hind>
				<Firma>Brainsphere</Firma>
				<Algus_Koht>Köping</Algus_Koht>
				<Lõpp_Koht>Marietta</Lõpp_Koht>
				<FirmaRating>2</FirmaRating>
				<Ekskursioonid>258</Ekskursioonid>
				<Majutus>2103</Majutus>
			</Reis>
		</Transport>
	</Firma>
	<Firma>
		<Firma Name="Browsezoom" />
		<Transport>
			<Transport Type="United" />
			<Reis>
				<Lennujaam Name="Hatzfeldhaven Airport" />
				<Kuupaev>2023-11-22</Kuupaev>
				<Hind>1593</Hind>
				<Firma>Browsezoom</Firma>
				<Algus_Koht>San Nicolas</Algus_Koht>
				<Lõpp_Koht>Adrasmon</Lõpp_Koht>
				<FirmaRating>1</FirmaRating>
				<Ekskursioonid>617</Ekskursioonid>
				<Majutus>4317</Majutus>
			</Reis>
		</Transport>
	</Firma>
	<Firma>
		<Firma Name="Centidel" />
		<Transport>
			<Transport Type="United" />
			<Reis>
				<Lennujaam Name="Contadora Airport" />
				<Kuupaev>2024-01-31</Kuupaev>
				<Hind>268</Hind>
				<Firma>Centidel</Firma>
				<Algus_Koht>København</Algus_Koht>
				<Lõpp_Koht>Portela</Lõpp_Koht>
				<FirmaRating>5</FirmaRating>
				<Ekskursioonid>185</Ekskursioonid>
				<Majutus>1390</Majutus>
			</Reis>
		</Transport>
	</Firma>
	<Firma>
		<Firma Name="Chatterbridge" />
		<Transport>
			<Transport Type="Alaska" />
			<Reis>
				<Lennujaam Name="Sibi Airport" />
				<Kuupaev>2024-05-23</Kuupaev>
				<Hind>128</Hind>
				<Firma>Chatterbridge</Firma>
				<Algus_Koht>Itzer</Algus_Koht>
				<Lõpp_Koht>Wulijie</Lõpp_Koht>
				<FirmaRating>4</FirmaRating>
				<Ekskursioonid>803</Ekskursioonid>
				<Majutus>859</Majutus>
			</Reis>
		</Transport>
	</Firma>
	<Firma>
		<Firma Name="Cogibox" />
		<Transport>
			<Transport Type="American" />
			<Reis>
				<Lennujaam Name="Ostrava Leos Janácek Airport" />
				<Kuupaev>2024-08-25</Kuupaev>
				<Hind>148</Hind>
				<Firma>Cogibox</Firma>
				<Algus_Koht>Grand Rapids</Algus_Koht>
				<Lõpp_Koht>Tracal</Lõpp_Koht>
				<FirmaRating>5</FirmaRating>
				<Ekskursioonid>230</Ekskursioonid>
				<Majutus>3334</Majutus>
			</Reis>
		</Transport>
	</Firma>
	<Firma>
		<Firma Name="Dabshots" />
		<Transport>
			<Transport Type="United" />
			<Reis>
				<Lennujaam Name="Kebar Airport" />
				<Kuupaev>2024-06-24</Kuupaev>
				<Hind>341</Hind>
				<Firma>Dabshots</Firma>
				<Algus_Koht>Hekou</Algus_Koht>
				<Lõpp_Koht>Bogale</Lõpp_Koht>
				<FirmaRating>2</FirmaRating>
				<Ekskursioonid>172</Ekskursioonid>
				<Majutus>4435</Majutus>
			</Reis>
		</Transport>
	</Firma>
	<Firma>
		<Firma Name="Devbug" />
		<Transport>
			<Transport Type="JetBlue" />
			<Reis>
				<Lennujaam Name="Surgut Airport" />
				<Kuupaev>2024-01-14</Kuupaev>
				<Hind>162</Hind>
				<Firma>Devbug</Firma>
				<Algus_Koht>New York City</Algus_Koht>
				<Lõpp_Koht>Morales</Lõpp_Koht>
				<FirmaRating>1</FirmaRating>
				<Ekskursioonid>613</Ekskursioonid>
				<Majutus>2075</Majutus>
			</Reis>
		</Transport>
	</Firma>
	<Firma>
		<Firma Name="Dynabox" />
		<Transport>
			<Transport Type="Spirit" />
			<Reis>
				<Lennujaam Name="Big Trout Lake Airport" />
				<Kuupaev>2023-09-14</Kuupaev>
				<Hind>1916</Hind>
				<Firma>Dynabox</Firma>
				<Algus_Koht>Jiuxian</Algus_Koht>
				<Lõpp_Koht>Allen</Lõpp_Koht>
				<FirmaRating>5</FirmaRating>
				<Ekskursioonid>805</Ekskursioonid>
				<Majutus>3295</Majutus>
			</Reis>
		</Transport>
	</Firma>
	<Firma>
		<Firma Name="Dynava" />
		<Transport>
			<Transport Type="United" />
			<Reis>
				<Lennujaam Name="Prince Abdulmohsin Bin Abdulaziz Airport" />
				<Kuupaev>2024-09-09</Kuupaev>
				<Hind>309</Hind>
				<Firma>Dynava</Firma>
				<Algus_Koht>Hallsberg</Algus_Koht>
				<Lõpp_Koht>Kujang</Lõpp_Koht>
				<FirmaRating>1</FirmaRating>
				<Ekskursioonid>353</Ekskursioonid>
				<Majutus>1243</Majutus>
			</Reis>
		</Transport>
	</Firma>
	<Firma>
		<Firma Name="Eadel" />
		<Transport>
			<Transport Type="United" />
			<Reis>
				<Lennujaam Name="Akiachak Airport" />
				<Kuupaev>2024-05-27</Kuupaev>
				<Hind>184</Hind>
				<Firma>Eadel</Firma>
				<Algus_Koht>Stockholm</Algus_Koht>
				<Lõpp_Koht>Sagopshi</Lõpp_Koht>
				<FirmaRating>5</FirmaRating>
				<Ekskursioonid>214</Ekskursioonid>
				<Majutus>4693</Majutus>
			</Reis>
		</Transport>
	</Firma>
	<Firma>
		<Firma Name="Eare" />
		<Transport>
			<Transport Type="Alaska" />
			<Reis>
				<Lennujaam Name="Lake Rudolf Airport" />
				<Kuupaev>2024-07-17</Kuupaev>
				<Hind>1303</Hind>
				<Firma>Eare</Firma>
				<Algus_Koht>Krikil</Algus_Koht>
				<Lõpp_Koht>Shchastya</Lõpp_Koht>
				<FirmaRating>1</FirmaRating>
				<Ekskursioonid>467</Ekskursioonid>
				<Majutus>2033</Majutus>
			</Reis>
		</Transport>
	</Firma>
	<Firma>
		<Firma Name="Eimbee" />
		<Transport>
			<Transport Type="JetBlue" />
			<Reis>
				<Lennujaam Name="Adirondack Regional Airport" />
				<Kuupaev>2024-08-29</Kuupaev>
				<Hind>406</Hind>
				<Firma>Eimbee</Firma>
				<Algus_Koht>Kudang</Algus_Koht>
				<Lõpp_Koht>Tuupovaara</Lõpp_Koht>
				<FirmaRating>5</FirmaRating>
				<Ekskursioonid>328</Ekskursioonid>
				<Majutus>2875</Majutus>
			</Reis>
		</Transport>
	</Firma>
	<Firma>
		<Firma Name="Feedfire" />
		<Transport>
			<Transport Type="Alaska" />
			<Reis>
				<Lennujaam Name="Awassa Airport" />
				<Kuupaev>2023-11-14</Kuupaev>
				<Hind>461</Hind>
				<Firma>Feedfire</Firma>
				<Algus_Koht>Nevel’</Algus_Koht>
				<Lõpp_Koht>Krasnyy Oktyabr’</Lõpp_Koht>
				<FirmaRating>3</FirmaRating>
				<Ekskursioonid>566</Ekskursioonid>
				<Majutus>2797</Majutus>
			</Reis>
		</Transport>
	</Firma>
	<Firma>
		<Firma Name="Flipopia" />
		<Transport>
			<Transport Type="United" />
			<Reis>
				<Lennujaam Name="Singleton Airport" />
				<Kuupaev>2024-07-23</Kuupaev>
				<Hind>350</Hind>
				<Firma>Flipopia</Firma>
				<Algus_Koht>Yiyang</Algus_Koht>
				<Lõpp_Koht>Palkovice</Lõpp_Koht>
				<FirmaRating>4</FirmaRating>
				<Ekskursioonid>883</Ekskursioonid>
				<Majutus>1135</Majutus>
			</Reis>
		</Transport>
	</Firma>
	<Firma>
		<Firma Name="Gabspot" />
		<Transport>
			<Transport Type="United" />
			<Reis>
				<Lennujaam Name="Zamperini Field" />
				<Kuupaev>2024-07-10</Kuupaev>
				<Hind>1948</Hind>
				<Firma>Gabspot</Firma>
				<Algus_Koht>Kristianstad</Algus_Koht>
				<Lõpp_Koht>Rostokino</Lõpp_Koht>
				<FirmaRating>1</FirmaRating>
				<Ekskursioonid>617</Ekskursioonid>
				<Majutus>1696</Majutus>
			</Reis>
		</Transport>
	</Firma>
	<Firma>
		<Firma Name="Gabtype" />
		<Transport>
			<Transport Type="Spirit" />
			<Reis>
				<Lennujaam Name="Baramita Airport" />
				<Kuupaev>2023-11-17</Kuupaev>
				<Hind>776</Hind>
				<Firma>Gabtype</Firma>
				<Algus_Koht>Lunel</Algus_Koht>
				<Lõpp_Koht>Di An</Lõpp_Koht>
				<FirmaRating>3</FirmaRating>
				<Ekskursioonid>577</Ekskursioonid>
				<Majutus>1185</Majutus>
			</Reis>
		</Transport>
	</Firma>
	<Firma>
		<Firma Name="Gigabox" />
		<Transport>
			<Transport Type="American" />
			<Reis>
				<Lennujaam Name="Linköping City Airport" />
				<Kuupaev>2024-08-04</Kuupaev>
				<Hind>841</Hind>
				<Firma>Gigabox</Firma>
				<Algus_Koht>Ta’ Xbiex</Algus_Koht>
				<Lõpp_Koht>Ouaoula</Lõpp_Koht>
				<FirmaRating>1</FirmaRating>
				<Ekskursioonid>277</Ekskursioonid>
				<Majutus>3820</Majutus>
			</Reis>
		</Transport>
		<Transport>
			<Transport Type="Southwest" />
			<Reis>
				<Lennujaam Name="Samjiyon Airport" />
				<Kuupaev>2024-07-11</Kuupaev>
				<Hind>872</Hind>
				<Firma>Gigabox</Firma>
				<Algus_Koht>Jutiapa</Algus_Koht>
				<Lõpp_Koht>Aioi</Lõpp_Koht>
				<FirmaRating>3</FirmaRating>
				<Ekskursioonid>797</Ekskursioonid>
				<Majutus>1791</Majutus>
			</Reis>
		</Transport>
	</Firma>
	<Firma>
		<Firma Name="Jatri" />
		<Transport>
